### ISSUE TITLE
Error if the name of site checked is the same as the name of existing folder 

### ISSUE THREAD

**Issue by kalia1962** [yaroslaff/showcert#1]
[temo@temo-z230 000]$ ls -l
total 0
[temo@temo-z230 000]$ showcert github.com
IP: 140.82.121.3
Names: github.com www.github.com
notBefore: 2023-02-14 00:00:00 (29 days old)
notAfter: 2024-03-14 23:59:59 (365 days left)
Issuer: C=US O=DigiCert Inc CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1
[temo@temo-z230 000]$ mkdir github.com
[temo@temo-z230 000]$ ls -l
total 4
drwxr-xr-x 2 temo temo 4096 Mar 15 17:23 github.com
[temo@temo-z230 000]$ showcert github.com
Traceback (most recent call last):
  File "/home/temo/.local/bin/showcert", line 459, in <module>
    main()
  File "/home/temo/.local/bin/showcert", line 451, in main
    rc = process_cert(CERT=cert, name=args.name, insecure=args.insecure, warn=args.warn, starttls=args.starttls)
  File "/home/temo/.local/bin/showcert", line 359, in process_cert
    chain = get_local_certs(CERT)
  File "/home/temo/.local/bin/showcert", line 227, in get_local_certs
    rawcert = open(CERT).read().encode()
IsADirectoryError: [Errno 21] Is a directory: 'github.com'

**Comment by kalia1962** [comment]
[temo@temo-z230 000]$ showcert -h
usage: showcert [-h] [-i] [--output OUTPUT] [-c] [-w [DAYS]] [-q] [-n NAME] [-t METHOD] [-l TIME] [--ca CA] CERT [CERT ...]

Show local/remote SSL certificate info v0.1.14

**Comment by yaroslaff** [comment]
Thank you for bugreport!
I fixed issue in new version (v0.1.15), you can get it from repo or `pip3 install -U showcert`
Now it works this way:
- If you have file (but not directory) in current directory, it prefers to check file. Otherwise, it checks host
- If you want to override it and check github.com, even while you have github.com file in current dir, use `--net` option to force network check.

Please confirm it's working for you.

**Comment by yaroslaff** [comment]
Closing as done (feature added, works for me).
